config/routes.rb
Rails.application.routes.draw do
  


  match "/auth/google_oauth2/callback" , to: 'google_auth#create', via: 'get'
  get "auth/failure", to: redirect('/')

  get 'scores/index'

  get 'sessions/new'
  root 'static_pages#dashboard'
  get 'static_pages/home'
  
  get 'static_pages/dashboard'
  get 'static_pages/analytics'



  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  


  resources :users do 
    collection do
      get :authenticate
    end
  end
  
  resources :teachers do 
    collection do 
      post :import
      get :to_google_sheet
      get :create_sheet
    end
  end
  resources :developments

  resources :schools do  
    collection do
      post :import 
      get :create_sheet_email
      get :create_sheet_sms
    end
    resources :conversations do
        put :increase_number
    end
  end

  resources :as_categories 
  
  resources :action_steps do 
    collection do
        post :import
    end
  end

  resources :programmes do
    get :update_spreadsheet
    resources :categories do 
      resources :criteria do 
        collection do 
          post :import
        end
      end
    
    end  
  end

  resources :in_people do
    get 'download', on: :member, constraints: {format: /(html|csv)/}
    post :add_exit_ticket
    post :add_question_answers
    post :create_attendance
    post :create_mulitple_attendances
    resources :attendances do
      collection do
        post :import
        get :edit_multiple
        put :update_multiple
      end
    end
    resources :exit_ticket_answers do
      collection do
        get :edit_all
        put :update_all
      end
    end
  end

  resources :exit_tickets do
      post :add_question
      resources :questions
  end

  resources :self_works do
    resources :submissions do
      collection do
        post :import
      end
    end

    resources :assignments
  end
  resources :observations do 
    resources :feedbacks do
      post :add_score
      post :add_lever
      collection do 
        post :import
        post :import_google
      end
       
    end
  end
  
  resources :programme_sessions do
    resources :in_people
    resources :self_works
    resources :observations
  end

  resources :scores, only: [:index]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/programme.rb
class Programme < ApplicationRecord
	has_many :developments, dependent: :destroy
	has_many :schools, through: :developments
	has_many :programme_sessions, dependent: :destroy
	has_many :sections, dependent: :destroy
	has_many :categories, through: :sections
	has_many :criteria, through: :categories
	has_many :conversations,  dependent: :destroy
	has_many :observations, through: :programme_sessions, as: :profile, dependent: :destroy, source: :profile, source_type: 'Observation'
	has_many :in_people, through: :programme_sessions, as: :profile, dependent: :destroy, source: :profile, source_type: 'InPerson'
	has_many :self_work, through: :programme_sessions, as: :profile, dependent: :destroy, source: :profile, source_type: 'SelfWork'
	has_many :scores, through: :criteria
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user
  def home
  end

  def dashboard
    @user = User.find(session["user_id"])
    @in_people = InPerson.order("date_done DESC").limit(10)
  end

  def analytics
  	@teachers = Teacher.school(params[:school_ids]) if params[:school_ids].present?
  	@teachers = @teachers.teacher_phase(params[:phases]) if params[:phases].present?
    @teachers = @teachers.observer(params[:observer]) if params[:observer].present?
    @teachers = @teachers.observation_order(params[:observation_orders]) if params[:observation_orders].present?
    @teachers = @teachers.paginate(per_page:10,page:params[:page]) if !@teachers.nil?

    @all_teachers = Teacher.where(nil)
    @all_teachers = @all_teachers.school(params[:school_ids]) if params[:school_ids].present?
    @all_teachers = @all_teachers.teacher_phase(params[:teacher_phase]) if params[:teacher_phase].present?
    @all_teachers = @all_teachers.observer(params[:observer]) if params[:observer].present?
    @all_teachers = @all_teachers.observation_order(params[:observation_order]) if params[:observation_order].present?
    

    @criteria = Criterium.where(nil)
  	@criteria = @criteria.category(params[:category]) if params[:category].present?
  	@criteria = @criteria.criterium(params[:criterium]) if params[:criterium].present?

  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/analytics.html.erb
<h1>Analytics</h1>
<div class= "col-md-12">
<div class="row">
<%= form_tag  static_pages_analytics_path(params["criterium"],params['teacher']), method: :get do %>
  <div class="col-md-2">
  	<%=select_tag :criterium,options_from_collection_for_select(Criterium.all, "id", "name"),prompt: "Instructional Techniques",class: 'form-control' %>
  </div>
  
  <div class="col-md-2">
  <%= select_tag :category,options_from_collection_for_select(Category.all,"id","name"),prompt: "Instructional Areas",class: 'form-control' %>
  </div>
   
  <div class="col-md-2">
    <%= select_tag :observer, options_from_collection_for_select(User.all,"id","name"),prompt: "Observer",class: 'form-control'%>
  </div>
</div>

<div class="row">
<div class = col-md-12>
  	<div class = "col-sm-3">
  	<h2> School</h2>
		<% School.where.not(name:"No School").all.each do |school| %>
		<div class="checkbox checkbox-primary">
		<%= check_box_tag "school_ids[]", school.id, checked = true, id: dom_id(school), class: 'checkbox checkbox-primary' %>
		<%= label_tag dom_id(school), school.name %><br>
		</div>
		<%end%>
	</div>
	
    <div class = "col-sm-3">
    <h2>Phase</h2>
    	<% phases = ["Foundation","Intermediate","Intermediate/Senior","Senior","Senior/FET","FET","Other"]%>
		<% phases.each do |phase| %>
		<div class="checkbox checkbox-primary">
			<%= check_box_tag "phases[]", phase, checked = true,id: phase, class: 'checkbox checkbox-primary' %>
			<%= label_tag phase, phase%><br>
		</div>
		<%end%>
	</div>
	<div class = "col-sm-3">
    <h2>Observation Number</h2>
    	<% observations = ["1","2","3","4","5"]%>
		<% observations.each do |observation| %>
		<div class="checkbox checkbox-primary">
			<%= check_box_tag "observations_orders[]", observation, checked = true,id: observation , class: 'checkbox checkbox-primary' %>
			<%= label_tag observation, "Observation #{observation}"%><br>
		</div>
		<%end%>
	</div>

	

</div>
</div>
<div class="row">



  
  <%= submit_tag "Filter Scores",class: 'btn btn-primary'%>
  </div>
</div>

<div class = "col-md-12">
<% if !params[:criterium].nil?||!params[:category].nil?||!params[:school].nil?||!params[:observation_number].nil?||!params[:teacher_phase].nil? ||!params[:observer].nil? %>
	<%if !params[:criterium].empty?%>
		<h2><%= Criterium.find(params["criterium"]).name %></h2>
	<%end%>

	<%if !params[:category].empty?%>
		<h2><%= Category.find(params["category"]).name %></h2>
	<%end%>

	<%if !params[:school_ids].nil?%>
		<% if params[:school_ids].count == School.count-1 %>
			<h2> All Schools </h2>
		<%else%>
		<h2>
			<% params["school_ids"].each do |school| %>
				<%= School.find(school).name %> 
			<%end%>
		</h2>
		<%end%>
	<%end%>

	<%if !params[:observations_orders].nil?%>
		<% if params[:observations_orders].count == 5%>
		<h2> All Observations </h2>
	 	<% else %>
			<h2> Observation numbers: <%= params[:observations_orders] %></h2>
			<%end%>
	<%end%>

	<%if !params[:phases].nil?%>
		<% if params[:phases].count == 7 %>
			<h2> All Phases </h2>
		<%else%>
		<h2>
			<% params[:phases].each do |phase| %>
			<%= phase %>
			<%end%>
		</h2>
		<%end%>
	<%end%>

	<%if !params[:observer].empty?%>
		<h2><%= User.find(params["observer"]).name%></h2>
	<%end%>

<% end %>
</div>



<div class="bs-example">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#averages">Averages</a></li>
        <li><a data-toggle="tab" href="#change">Change</a></li>
        <li><a data-toggle="tab" href="#highest">Highest</a></li>
        <li><a data-toggle="tab" href="#lowest">Lowest</a></li>
    </ul>
    <div class="tab-content">
        <div id="averages" class="tab-pane fade in active">
            <h3>Averages</h3>
           <div class ="col-md-6">
           <table class="table table-bordered">
				<thead>
					<tr>
						<th>
							Instruction Technique
						</th>
						<th>
							Averages
						</th>
					</tr>
				</thead>
				<tbody>
				<% @criteria.all.each  do |criterium| %>
					<tr>
						<td>
							<p><%=criterium.name%></p>
						</td>
						<td>
						<% if !@all_teachers.joins(:scores).where(scores: {criterium: criterium}).empty? %>
	    					<%=@all_teachers.joins(:scores).where(scores: {criterium: criterium}).average(:score_value).round(2)%>
	    				<% else %>
	    					-
	    				<%end%>
						</td>
					</tr>
				<%end%>

				</tbody>
			</table>
        </div>
        
        </div>
        <div id="change" class="tab-pane fade">
            <h3>Change</h3>
           <div class ="col-md-6">
           <table class="table table-bordered">
				<thead>
					<tr>
						<th>
							Instruction Technique
						</th>
						<th>
							Average
						</th>
					</tr>
				</thead>
				<tbody>

				<% @criteria.all.each  do |criterium| %>
					<tr>
						<td>
							<p><%=criterium.name%></p>
						</td>
						<td>
						<% if !@all_teachers.joins(:scores).where(scores: {criterium: criterium}).empty? %>
	    					<%=@all_teachers.joins(:scores).where(scores: {criterium: criterium}).average(:score_value).round(2)%>
	    				<% else %>
	    					-
	    				<%end%>
						</td>
					</tr>
				<%end%>
				</tbody>
			</table>
        </div>
        </div>
        <div id="highest" class="tab-pane fade">
            <h3>Highest</h3>
           <div class ="col-md-6">
           <table class="table table-bordered">
				<thead>
					<tr>
						<th>
							Instruction Technique
						</th>
						<th>
							Average
						</th>
					</tr>
				</thead>
				<tbody>
				<% @criteria.all.each  do |criterium| %>
					<tr>
						<td>
							<p><%=criterium.name%></p>
						</td>
						<td>
						<% if !@all_teachers.joins(:scores).where(scores: {criterium: criterium}).empty? %>
	    					<%=@all_teachers.joins(:scores).where(scores: {criterium: criterium}).maximum(:score_value).round(2)%>
	    				<% else %>
	    					-
	    				<%end%>
						</td>
					</tr>
				<%end%>
				</tbody>
			</table>
        </div>
        </div>
        <div id="lowest" class="tab-pane fade">
            <h3>Lowest</h3>
           <div class ="col-md-6">
           <table class="table table-bordered">
				<thead>
					<tr>
						<th>
							Instruction Technique
						</th>
						<th>
							Averages
						</th>
					</tr>
				</thead>
				<tbody>
				<% @criteria.all.each  do |criterium| %>
					<tr>
						<td>
							<p><%=criterium.name%></p>
						</td>
						<td>
						<% if !@all_teachers.joins(:scores).where(scores: {criterium: criterium}).empty? %>
	    					<%=@all_teachers.joins(:scores).where(scores: {criterium: criterium}).minimum(:score_value).round(2)%>
	    				<% else %>
	    					-
	    				<%end%>
						</td>
					</tr>
				<%end%>

				</tbody>
			</table>
        </div>
        </div>
        </div>
    </div>
</div>


<%end%>

<% if !@teachers.nil? %>
<%= will_paginate @teachers %>

<table class= "table-bordered">
	<thead>
		<tr>
			<th>Teachers</th>
			<% @criteria.all.each  do |criterium| %>
	      		<th><p><%=criterium.name%></p>
	      	</th>
	      	<%end%>
	    </tr>

	</thead>
	<tbody>
		<tr>
		<% @teachers.each do |teacher| %>
			<td>
				<%=teacher.full_name%>
			</td>
			<% @criteria.all.each do |criterium| %>
			<% average_scores = [] %>
			<td>
				<% if !teacher.scores.where(criterium:criterium).empty? %>
					<% if params[:calculations] == "Average" %> 
					<%= score =  teacher.scores.where(criterium: criterium).average(:score_value).round(1)%>
					<% average_scores << score %>

					<% elsif params[:calculations] == "Highest" %> 
					<%= score =  teacher.scores.where(criterium: criterium).maximum(:score_value).round(1)%>
					<% average_scores << score %>

					<% elsif params[:calculations] == "Lowest" %> 
					<%= score =  teacher.scores.where(criterium: criterium).minimum(:score_value).round(1)%>
					<% average_scores << score %>

					<% elsif params[:calculations] == "Growth" %> 
					<%= score =  teacher.scores.where(criterium: criterium).average(:score_value).round(1)%>
					<% average_scores << score %>
					<%end%>
				<%else%>
				-
				<%end%>
			</td>

			<%end%>
			<% if params[:category].present? %>
			<td>
				<% if !teacher.scores.joins(:criterium).where(criteria: {category_id: params[:category]}).empty?%>
				<%= teacher.scores.joins(:criterium).where(criteria:{category_id: params[:category]}).average(:score_value).round(2) %>
				<%end%>
			</td>
			<%end%>
		</tr>
		<%end%>		
	</tbody>
	
</table>
<%= will_paginate @teachers %>

<% end %>

app/views/static_pages/dashboard.html.erb
<section class="content-header">
  <h1>
  Dashboard
  </h1>
</section>
<!-- Main content -->
<section class="content">
  <!-- Info boxes -->
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
        <%= link_to teachers_path do %>
      <div class="info-box">
        <span class="info-box-icon bg-grey"><i class="fa fa-pencil"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">Teachers</span>
          <span class="info-box-number"><%= Teacher.count%><small></small></span>
        <%end%>
      </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-4 col-sm-6 col-xs-12">
      <%= link_to programmes_path do %>
      <div class="info-box">
        <span class="info-box-icon bg-burntred"><i class="fa fa-institution"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">Programmes</span>
          <span class="info-box-number"><%= Programme.count %></span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <% end %>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <%= link_to programme_sessions_path do %>
      <div class="info-box">
        <span class="info-box-icon bg-gold"><i class="fa fa-envelope"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">Sessions</span>
          <span class="info-box-number"><%= ProgrammeSession.count%></span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <%end%>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <!-- /.col -->
  </div>
  <!-- /.row -->
  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <div class="col-md-12">
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">Latest Sessions</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="table-responsive">
            <table class="table no-margin">
              <thead>
                <tr>
                  <th>Session Date</th>
                  <th>School</th>
                  <th>Session Name</th>
                  <th>Number Present</th>
                </tr>
              </thead>
              <tbody>
                <% @in_people.all.each do |session| %>
                <tr>
                  <td><%=session.date_done%></td>
                  <td><%= link_to session.programme_session.school.name, session.programme_session.school %></td>
                  <td><%= link_to session.name, session %></td>
                  <td><%= session.attendances.where(attendance_value:"Present").count%></td>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
          <!-- /.table-responsive -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
          <%= link_to "New Session", new_programme_session_path, class: "btn btn-sm btn-primary btn-flat pull-left"%>
          <%= link_to "View All Sessions", programme_sessions_path, class: "btn btn-sm btn-default btn-flat pull-right"%>
        </div>
        <!-- /.box-footer -->
      </div>
      
    </div>
    <!--/.box -->
  </div>
  <!-- /.col -->
<!-- /.row -->
</section>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
	<title><%=yield(:title)%> | Database</title>
</head>
<body>


<div class="center jumbotron">
  <h1>Welcome to Database</h1>
  <p>Please <%=link_to "log in", login_path %> </p>
</div>




</body>
</html>