config/routes.rb
Rails.application.routes.draw do
  


  match "/auth/google_oauth2/callback" , to: 'google_auth#create', via: 'get'
  get "auth/failure", to: redirect('/')

  get 'scores/index'

  get 'sessions/new'
  root 'static_pages#dashboard'
  get 'static_pages/home'
  
  get 'static_pages/dashboard'
  get 'static_pages/analytics'



  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  


  resources :users do 
    collection do
      get :authenticate
    end
  end
  
  resources :teachers do 
    collection do 
      post :import
      get :to_google_sheet
      get :create_sheet
    end
  end
  resources :developments

  resources :schools do  
    collection do
      post :import 
      get :create_sheet_email
      get :create_sheet_sms
    end
    resources :conversations do
        put :increase_number
    end
  end

  resources :as_categories 
  
  resources :action_steps do 
    collection do
        post :import
    end
  end

  resources :programmes do
    get :update_spreadsheet
    resources :categories do 
      resources :criteria do 
        collection do 
          post :import
        end
      end
    
    end  
  end

  resources :in_people do
    get 'download', on: :member, constraints: {format: /(html|csv)/}
    post :add_exit_ticket
    post :add_question_answers
    post :create_attendance
    post :create_mulitple_attendances
    resources :attendances do
      collection do
        post :import
        get :edit_multiple
        put :update_multiple
      end
    end
    resources :exit_ticket_answers do
      collection do
        get :edit_all
        put :update_all
      end
    end
  end

  resources :exit_tickets do
      post :add_question
      resources :questions
  end

  resources :self_works do
    resources :submissions do
      collection do
        post :import
      end
    end

    resources :assignments
  end
  resources :observations do 
    resources :feedbacks do
      post :add_score
      post :add_lever
      collection do 
        post :import
        post :import_google
      end
       
    end
  end
  
  resources :programme_sessions do
    resources :in_people
    resources :self_works
    resources :observations
  end

  resources :scores, only: [:index]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/observation.rb
class Observation < ApplicationRecord
	has_one :programme_session,:as => :profile,dependent: :destroy
	has_many :categories, through: :sections
	has_many :feedbacks, dependent: :destroy
	has_many :scores, through: :feedbacks
	has_many :takeaways, through: :feedbacks
	has_many :criteria, through: :categories




	
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  before_action :logged_in?, only: [:show,:edit, :update, :index]
  before_action :find_as_observation, only:[:edit,:update,:show,:destroy]
  def new
    @observation = Observation.new
  end

  def create
    @observation = Observation.new(observation_params)
    if @observation.save
      redirect_to @observation, notice: "Session successfully created."
    end
  end


  def edit
    @observation = Observation.find(params[:id])

  end

  def update
    @observation = Observation.find(params[:id])
    if @observation.update_attributes(observation_params)
      redirect_to @observation, notice: "Session has been updated successfully"
    end
  end


  def show

    @observation = Observation.find(params[:id])
     @programme = @observation.programme_session.programme
    @feedbacks = @observation.feedbacks
    respond_to do |format|
        format.html
        format.csv {send_data @feedbacks.to_csv, filename: "#{@observation.name}_#{@observation.programme_session.school.name}_observations.csv"}
    end
    

  end

  def index
    @observations = Observation.all
  end

  def destroy
    @observation.destroy
    redirect_to programme_sessions_path
  end

  private

  def find_as_observation
    @observation = Observation.find(params[:id])
  end

  def observation_params
    params.require(:observation).permit(:name, :done, :observation_type, :observation_order)
  end
  
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/views/observations/_form.html.erb
<div class="form-body">
<%= form_for(@observation) do |f| %>  
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>

  <div class="form-group">
    <%= f.label :observation_order %>
    <%= f.select :observation_order, options_for_select(1..5), class: "form-control" %>
  </div>

  	<div class="form-group">
    	<%= f.label :observation_type, "Category:" %>
    	<%= f.select :observation_type, ['In Class','Simulation'], :prompt => '-- Select One --', :required => true, class: "form-control" %>
  </div>



    <%= f.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>
  </div>

app/views/observations/edit.html.erb
<%provide(:button_text, "Update Session") %>
<section class="content">
<div class="row">
<div class="col-md-12">
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Edit Session</h3>
    <div class="box-tools pull-right">
      <!-- Buttons, labels, and many other things can be placed here! -->
      <!-- Here is a label for example -->
      
    </div>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  <div class="box-body">
   <%= render 'form'%>
  </div>
  <!-- /.box-body -->


</div>
<!-- /.box -->
</div>
</div>
</section>

app/views/observations/index.html.erb
<h1>All Observations</h1>
<% School.all.each do |school| %>
<div class="row">
	<div class="col-lg-4">
		<div class="panel panel-default">
		    <div class="panel-heading">
		        <%= school.name %>
		    </div>
		    <div class="panel-body">
		       	<% school.programme_sessions.where(profile_type: "Observation").last(5).each do |observation| %>
		        <p><%= link_to observation.profile.name, observation.profile %></p>
		        	<%end%>
		        	<%= link_to "See More", school %>
		    </div>
		    <!-- /.panel-body -->
		</div>
		<!-- /.panel -->
		
<%end%>
	</div>	

app/views/observations/new.html.erb
<%provide(:button_text, "Create Session") %>
<section class="content">
<div class="row">
<div class="col-md-12">
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Create Session</h3>
    <div class="box-tools pull-right">
      <!-- Buttons, labels, and many other things can be placed here! -->
      <!-- Here is a label for example -->
      
    </div>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  <div class="box-body">
   <%= render 'form'%>
  </div>
  <!-- /.box-body -->


</div>
<!-- /.box -->
</div>
</div>
</section>

app/views/observations/show.html.erb
<section class="content">
	<div class="row">
		<div class="col-md-4">
			<!-- Profile Image -->
			<div class="box box-default">
				<div class="box-body box-profile">
					
					<h3 class="profile-username text-center"><%= @observation.name%></h3>
					<ul class="list-group list-group-unbordered">
						<li class="list-group-item">
							<b>Programme Nane</b> <p class="pull-right"><%= link_to @observation.programme_session.programme.name, @observation.programme_session.programme %></p>
						</li>
						<li class="list-group-item">
							<b>Observation Order</b> <p class="pull-right"><%= @observation.observation_order %></p>
						</li>
						<li class="list-group-item">
							<b>School</b> <%=link_to @observation.programme_session.school.name,
							@observation.programme_session.school,class: "pull-right" %>
						</li>
						<li class="list-group-item">
							<b>Session Type</b> <p class="pull-right"><%= @observation.observation_type %></p>
						</li>
					</ul>
					<div class="box-footer clearfix">
						<div class="row no-print">
							<div class="col-xs-12">
								<div class="button-group">
								
								<%= link_to "Edit Session", edit_observation_path(@observation), class: "btn btn-sm btn-primary"%>
							</div>
							<div class="button-group">
								<%= link_to "Change Programme", edit_programme_session_path(@observation.programme_session), class: "btn btn-sm btn-primary" %>
								<%= link_to "Delete Session", @observation, method: :delete,class: "btn btn-sm btn-danger",
								data: { confirm: "You sure?" }  %>
							</div>
							</div>
						</div>
					</div>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">Instructional Areas</h3>
					<div class="box-tools pull-right">
						<!-- Buttons, labels, and many other things can be placed here! -->
						<!-- Here is a label for example -->
						<%= link_to "Add New Category",  new_programme_category_path(@programme), class: "btn btn-sm btn-default" %>
					</div>
					<!-- /.box-tools -->
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					<ul>
						<% @programme.categories.each do |category| %>
						<li>
							<%= link_to category.name, programme_category_path(@programme,category) %>
							<% category.criteria.all.each do |criterium| %>
							<p style="text-indent:10px"><%= link_to criterium.name, programme_category_criterium_path(@programme,category,criterium) %>
							| <%= @observation.scores.where(criterium: criterium).average(:score_value).round(2) unless @observation.scores.where(criterium: criterium).average(:score_value).nil?  %></p>
							<%end%>
						</li>
						<%end%>
					</ul>
					
				</div>
				<!-- /.box-body -->
</div>
		</div>
		<div class="col-md-8">
			<div class="box box-default">
				<div class="box-header with-border">
					<h3 class="box-title">Observations Done</h3>
				
				<div class="box-tools pull-right">
					<!-- Buttons, labels, and many other things can be placed here! -->
					<!-- Here is a label for example -->
					<%= link_to "Export Scores CSV", observation_path(format: "csv"), class: "btn btn-sm btn-default" %>
					<%= link_to "Add Feedback", new_observation_feedback_path(@observation) ,class: "btn btn-sm btn-default" %>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					<% @observation.feedbacks.each do |feedback| %>
					
					<p><%= link_to feedback.teacher.full_name, observation_feedback_path(@observation,feedback) unless feedback.teacher.nil? %> | <%= @observation.programme_session.school.name%> | <%= feedback.observation_done.to_date unless feedback.observation_done.nil? %> <%=link_to "Edit", edit_observation_feedback_path(@observation,feedback),class: "label label-primary" %>
						<%= link_to "Delete", observation_feedback_path(@observation,feedback), method: :delete, class: "label label-danger",
								data: { confirm: "You sure?" }  %>
					<%end%>
				</div>
				<!-- /.box-body -->
			</div>
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">Import Feedback</h3>
					<div class="box-tools pull-right">
						<!-- Buttons, labels, and many other things can be placed here! -->
						<!-- Here is a label for example -->
						
					</div>
					<!-- /.box-tools -->
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					<%= form_tag import_observation_feedbacks_path(@observation), multipart: true do %>
					<%= file_field_tag :file, class: "form-control" %>
					<%= submit_tag "Import", class: "form-control" %>
					<%end%>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
			<!-- /.col -->
			
			
		</div>
		<!-- /.col -->
		<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Import from Google</h3>
    <div class="box-tools pull-right">
      <!-- Buttons, labels, and many other things can be placed here! -->
      <!-- Here is a label for example -->
      
    </div>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  <div class="box-body">
  	<div class="form-group">
	<%= form_tag  import_google_observation_feedbacks_path(@observation, @feedback), multipart: true do %>
  	
  	<div class="form-group">
  		<%= label_tag "Enter Document Url",:url, class: "form-control"%>
  	<%=text_field_tag :url,nil,placeholder:'Enter Url',class: "form-control"%>

  </div>
  	<div class = "form-group">
    	<% @observation.programme_session.programme.categories.all.each do |category| %>
      <%= hidden_field_tag "programme[categories][]" %>
      <%= check_box_tag "programme[categories][]", category.name, name: dom_id(category) %>
  		<%= label_tag dom_id(category), category.name %><br>
    	<%end%>
    

  </div>
  	<%= submit_tag "Add Feedback", class: "btn btn-primary" %>
 
</div>

<% end %>
  
  <!-- /.box-body -->

</div>
	</div>
	<!-- /.row -->
</section>