config/routes.rb
Rails.application.routes.draw do
  


  match "/auth/google_oauth2/callback" , to: 'google_auth#create', via: 'get'
  get "auth/failure", to: redirect('/')

  get 'scores/index'

  get 'sessions/new'
  root 'static_pages#dashboard'
  get 'static_pages/home'
  
  get 'static_pages/dashboard'
  get 'static_pages/analytics'



  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  


  resources :users do 
    collection do
      get :authenticate
    end
  end
  
  resources :teachers do 
    collection do 
      post :import
      get :to_google_sheet
      get :create_sheet
    end
  end
  resources :developments

  resources :schools do  
    collection do
      post :import 
      get :create_sheet_email
      get :create_sheet_sms
    end
    resources :conversations do
        put :increase_number
    end
  end

  resources :as_categories 
  
  resources :action_steps do 
    collection do
        post :import
    end
  end

  resources :programmes do
    get :update_spreadsheet
    resources :categories do 
      resources :criteria do 
        collection do 
          post :import
        end
      end
    
    end  
  end

  resources :in_people do
    get 'download', on: :member, constraints: {format: /(html|csv)/}
    post :add_exit_ticket
    post :add_question_answers
    post :create_attendance
    post :create_mulitple_attendances
    resources :attendances do
      collection do
        post :import
        get :edit_multiple
        put :update_multiple
      end
    end
    resources :exit_ticket_answers do
      collection do
        get :edit_all
        put :update_all
      end
    end
  end

  resources :exit_tickets do
      post :add_question
      resources :questions
  end

  resources :self_works do
    resources :submissions do
      collection do
        post :import
      end
    end

    resources :assignments
  end
  resources :observations do 
    resources :feedbacks do
      post :add_score
      post :add_lever
      collection do 
        post :import
        post :import_google
      end
       
    end
  end
  
  resources :programme_sessions do
    resources :in_people
    resources :self_works
    resources :observations
  end

  resources :scores, only: [:index]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/self_work.rb
class SelfWork < ApplicationRecord
	has_one :programme_session,:as => :profile,dependent: :destroy
	has_many :submissions
	has_many :assignments

	scope :programme, -> (programme) {joins(programme_session: :programme).where(programme_sessions: {programme: programme})}
	scope :school, -> (school) {joins(programme_session: :school).where(programme_sessions:{school:school})}
end

app/controllers/self_works_controller.rb
class SelfWorksController < ApplicationController
    before_action :logged_in_user
    before_action :find_as_self_work, only: [:edit,:show,:destroy,:update]
  
  def new
    @self_work = SelfWork.new
  end

  def create
    @self_work = SelfWork.new(self_work_params)
    if @self_work.save 

      flash[:success] = "Session Created"
      redirect_to @self_work
    end
  end

  def edit
  end

  def show
    @submissions = @self_work.submissions

    respond_to do |format|
      format.html
      format.csv{send_data @submissions.to_csv, filename: "#{@self_work.name}_submissions.csv"}
    end
    @assignments = @self_work.assignments
  end

  def index
    @self_works = SelfWork.all
  end


  def destroy
    @self_work.destroy
    flash[:success] = "Session Deleted"
    redirect_to programme_sessions_path
  end

  def update
    if @self_work.update_attributes(self_work_params)
   
      redirect_to @self_work
    end
  end

  private

  def find_as_self_work
    @self_work = SelfWork.find(params[:id])
  end

  def self_work_params
    params.require(:self_work).permit(:name)
  end


  
  


end

app/helpers/self_works_helper.rb
module SelfWorksHelper
end

app/views/self_works/_form.html.erb
<div class="form-body">
<%= form_for(@self_work) do |f| %>  
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>


    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>
</div>

app/views/self_works/edit.html.erb
<%provide(:button_text, "Update Session") %>
<section class="content">
<div class="row">
<div class="col-md-12">
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Edit Session</h3>
    <div class="box-tools pull-right">
      <!-- Buttons, labels, and many other things can be placed here! -->
      <!-- Here is a label for example -->
    </div>
    <!-- /.box-tools -->
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <%= render 'form' %>
  </div>
</div>
</div>
</div>
</section>
<!-- /.box -->

app/views/self_works/new.html.erb
<%provide(:button_text, "Create Session") %>
<h1>Create Self Work Session</h1>

<%= render 'form' %>

app/views/self_works/show.html.erb
<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-md-4">
			<!-- Profile Image -->
			<div class="box box-default">
				<div class="box-body box-profile">
					
					<h3 class="profile-username text-center"><%= @self_work.name %></h3>
					<ul class="list-group list-group-unbordered">
						<li class="list-group-item">
							<b>Programme Name</b> <p class="pull-right"><%= @self_work.programme_session.programme.name %></p>
						</li>
						<li class="list-group-item">
							<b>School</b> <a class="pull-right"><%= @self_work.programme_session.school.name%></a>
						</li>
					</ul>
					<div class="box-footer clearfix">
						<div class="row no-print">
							<div class="col-xs-12">
								<%= link_to "Edit Session", edit_self_work_path(@self_work),class: "btn btn-sm btn-primary"%>
								<%= link_to "Change Programme", edit_programme_session_path(@self_work.programme_session),class: "btn btn-sm btn-primary" %>
								<%= link_to "Delete Session", @self_work,class: "btn btn-sm btn-danger", method: :delete,
								data: { confirm: "You sure?" }  %>
							</div>
						</div>
					</div>
				</div>
				<!-- /.box-body -->
			</div>

			<div class="box box-default">
				<div class="box-body box-profile">
					
					<h3 class="profile-username text-center">Import Submissions</h3>
							<%= form_tag import_self_work_submissions_path(@self_work,@submission), multipart: true do %>
	<%= file_field_tag :file %>
	<%= submit_tag "Import" %>
	<% end %>
					
				</div>
				<!-- /.box-body -->
			</div>
						<div class="box box-default">
				<div class="box-body box-profile">
					
					<h3 class="profile-username text-center">Assignments</h3>
					<% if @self_work.assignments.any?%>
						<div class= "teacher-submission">
							<%= render @assignments %>
						</div>
						<% end %>		
					
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
			<!-- About Me Box -->
		</div>
		<div class="col-md-8">
			<div class="box box-default">
				<div class="box-header with-border">
					<h3 class="box-title">Submissions Information</h3>
					<div class="box-tools pull-right">
						<!-- Buttons, labels, and many other things can be placed here! -->
						<!-- Here is a label for example -->
						<%= link_to "Add Submission", new_self_work_submission_path(@self_work),class: "btn btn-sm btn-default" %>
						<%= link_to "Add Assignment", new_self_work_assignment_path(@self_work), class: "btn btn-sm btn-default" %>
						<%= link_to "Download Submissions CSV", self_work_submissions_path(@self_work,format: "csv"), class: " btn btn-sm btn-default" %>
					</div>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					<div>
						<% if @self_work.submissions.any?%>
						<div class= "teacher-submission">
							<%= render @submissions %>
						</div>
						<% end %>
					</div>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
			<!-- /.col -->
			
			
		</div>
		<!-- /.col -->
	</div>
	<!-- /.row -->
</section>