config/routes.rb
Rails.application.routes.draw do
  


  match "/auth/google_oauth2/callback" , to: 'google_auth#create', via: 'get'
  get "auth/failure", to: redirect('/')

  get 'scores/index'

  get 'sessions/new'
  root 'static_pages#dashboard'
  get 'static_pages/home'
  
  get 'static_pages/dashboard'
  get 'static_pages/analytics'



  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  


  resources :users do 
    collection do
      get :authenticate
    end
  end
  
  resources :teachers do 
    collection do 
      post :import
      get :to_google_sheet
      get :create_sheet
    end
  end
  resources :developments

  resources :schools do  
    collection do
      post :import 
      get :create_sheet_email
      get :create_sheet_sms
    end
    resources :conversations do
        put :increase_number
    end
  end

  resources :as_categories 
  
  resources :action_steps do 
    collection do
        post :import
    end
  end

  resources :programmes do
    get :update_spreadsheet
    resources :categories do 
      resources :criteria do 
        collection do 
          post :import
        end
      end
    
    end  
  end

  resources :in_people do
    get 'download', on: :member, constraints: {format: /(html|csv)/}
    post :add_exit_ticket
    post :add_question_answers
    post :create_attendance
    post :create_mulitple_attendances
    resources :attendances do
      collection do
        post :import
        get :edit_multiple
        put :update_multiple
      end
    end
    resources :exit_ticket_answers do
      collection do
        get :edit_all
        put :update_all
      end
    end
  end

  resources :exit_tickets do
      post :add_question
      resources :questions
  end

  resources :self_works do
    resources :submissions do
      collection do
        post :import
      end
    end

    resources :assignments
  end
  resources :observations do 
    resources :feedbacks do
      post :add_score
      post :add_lever
      collection do 
        post :import
        post :import_google
      end
       
    end
  end
  
  resources :programme_sessions do
    resources :in_people
    resources :self_works
    resources :observations
  end

  resources :scores, only: [:index]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/navigation/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
   Data is private and confidential
  </div>
  <strong>
    2018
    <a href="https://instill.education"> Instill Education</a>
  </strong>
 
</footer>

app/views/layouts/navigation/_header.html.erb
<header class="main-header">
    <!-- Logo -->
    <%= link_to root_path, class: "logo" do %>
      <!-- mini logo for sidebar mini 50x50 pixels -->

      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Instill </b>Data Portal</span>
    <%end%>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
    <% if logged_in?%>
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span><%= current_user.name%></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">

                <p><%= current_user.name%>
                </p>
              </li>
              <!-- Menu Body -->

              <!-- Menu Footer-->
              <li class="user-footer">

                  <%= link_to "Profile" ,current_user,class: "btn btn-default btn-flat" %>               

                  <%= link_to "Users", users_url, class: "btn btn-default btn-flat"%>

                  <%= link_to "Sign out", logout_path, method: :delete, class: "btn btn-default btn-flat"%>
              </li>
            </ul>
          </li>
        </ul>
        <%end%>
        
      </div>
    </nav>
  </header>

app/views/layouts/navigation/_layout.html.erb
<%= render "layouts/navigation/header" %>
<% if logged_in? %>
<%= render "layouts/navigation/side_bar" %>
<%end%>

app/views/layouts/navigation/_side_bar.html.erb
<div class="main-sidebar">
  <div class="sidebar">
    <ul class="sidebar-menu">
      <li class="header">
        SCHOOL INFORMATION
      </li>
      <li>
        <%= link_to teachers_path do %>
          Teachers 
        <%end%>
      </li>
      <li>
      <%= link_to schools_path do %>
          Schools 
        <%end%>
      </li>
      <li class="header">
        SESSIONS
      </li>
      <li>
          <%= link_to programme_sessions_path do %>
          All Sessions 
        <%end%>
      </li>
      <li>
        <%= link_to new_programme_session_path do %>
        Create New Session
        <%end%>
      </li>
      <li class="header">
        PROGRAMMES INFOMATION
      </li>
      <li>
        <%= link_to programmes_path do %>
        Programmes
        <%end%>
      </li>
      <li>
        <%= link_to action_steps_path do %>
        <span>Action Steps</span>
        <%end%>
      </li>
      <li>
        <%= link_to exit_tickets_path do %>
        <span>Exit Tickets</span>
        <%end%>
      </li>                              
    </ul>
  </div>
</div>